-- ============================================================
-- SmartCare 360 — data.sql
-- Admin is NOT seeded here (created from SMARTCARE_ADMIN_* env vars).
-- Demo users and catalogs are created by DataInitializer only when missing.
-- Live records persist in the application database and are not published.
-- ============================================================
